project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - 0_setup.qmd
    - 1_intro.qmd
    - 2_data.qmd
    - 3_aodp.qmd
    - 4_rust.qmd

execute:
  # run *all* code chunks from the folder containing your _quarto.yml
  working-dir: .

website:
  navbar:
    title: |
      Identification of Rust Fungal Species Using Metabarcoding and AODP<br>
      <span class="navbar-subtitle">
        <img src="images/cps-logo.png" alt="CPS logo" class="cps-logo">
          Canadian Phytopathological Society
      </span><br>
      <span class="navbar-subtitle">
        <img src="images/ICRPMC2025-wheat-logo.png" alt="ICRPMC2025-wheat logo" class="ICRPMC2025-wheat-logo">
          17th International Cereal Rusts and Powdery Mildews Conference (ICRPMC2025)
      </span><br>
      <span class="navbar-subtitle">
        <img src="images/BGRI-logo.png" alt="BGRI logo" class="BGRI-logo">
          Bourlag Global Rust Initiative (BGRI) Technical Workshop
      </span><br>
    pinned: true
    right:
    - text: Workshop Content
      menu:
        - href: index.qmd
          text: The workshop
        - href: 0_setup.qmd
          text: Environment Setup
        - href: 1_intro.qmd
          text: Introduction
        - href: 2_data.qmd
          text: The Dataset
        - href: 3_aodp.qmd
          text: AODP for Classification
        - href: 4_rust.qmd
          text: Validation & Visulization

format:
  html:
    csl: chicago-author-date.csl
    citations: true
    theme:
      - cosmo
      - brand
      - flatly
    code-fold: false
    code-overflow: wrap
    code-tools:
      toggle: false      # hides the `</> Code` button
      source: false      # prevents source code toggle
    highlight-style: github
    css: tutorial.css
    toc: true # enable local TOC
    toc-location: left # place toc to the left (default is on the right)
    toc_float: false # force it into the left column
    #  collapsed: false
    toc_depth: 2
    includes:
      before_body: header.html

filters:
  - custom-callout
  
# Define custom callouts here
custom-callout:
  bashblock:
    title: "BASH Block"
    icon-symbol: "💻"
    color: "#00008B"
  rblock:
    title: "R Block"
    icon-symbol: "📊"
    color: "#228B22"



bibliography: bibtexlib.bib

editor: visual


